# Use root/example as user/password credentials

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb+srv://giovannileao:y6ty8BHzjDIWEO3e@cluster0.yn8pwrg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      ME_CONFIG_BASICAUTH: false
